# This workflow will install Python dependencies, run tests and lint/formatting - possibly with a variety of Python versions - bump version, re-commit  publish to PYPI
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Publish Python package

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.ipynb'
      - '**.json'
      - '.vscode'
      - 'scripts'
      - 'tests'
      - 'notebooks'
      - '**.md'
      - '**.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
      
jobs:
  package:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9"]
    permissions: write-all

    steps:
    
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0
        fetch-tags: true

    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        update-python: true
        cache: true
          
    - name: Install dependencies
      run: |
        pdm install -G dev
        
    - name: Test, format, lint
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DBHUB_API_KEY: ${{ secrets.DBHUB_API_KEY }}
        CODE_OCEAN_API_TOKEN: ${{ secrets.CODE_OCEAN_API_TOKEN }}
        CODE_OCEAN_DOMAIN: ${{ secrets.CODE_OCEAN_DOMAIN }}
      run: |
        mkdir .mypy_cache
        pdm run prebuild
        
    - name: Bump project version
      run: |
        pdm run bumpver
      
    - name: Add requirements.txt
      run: |
        pdm export --without-hashes --prod -o requirements.txt
    
    - name: Pull
      # pull in case non-packaged files were changed since job started (packaged
      # files would trigger a new job and cancel this one)
      run: |
        git stash
        git pull --rebase
        git stash pop
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "Bump [skip actions]"
        author_name: Ben Hardcastle
        author_email: ben.hardcastle@alleninstitute.org
        # if the default github actions bot is used, we can't trigger other
        # workflows
        
    - name: Tag commit
      run: |
        pdm run tag
        git push --tags 

    - name: Publish
      run: |
        pdm publish

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  update_cache:
    needs: package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]
    permissions: write-all

    steps:

    - name: Launch
      continue-on-error: true
      env:
        DBHUB_API_KEY: ${{ secrets.DBHUB_API_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CODE_OCEAN_API_TOKEN: ${{ secrets.CODE_OCEAN_API_TOKEN }}
        CODE_OCEAN_DOMAIN: ${{ secrets.CODE_OCEAN_DOMAIN }}
      run: |
        pip install npc_lims
        run_session_cache_capsule
